### PR TITLE
Add padding to input fields to not overlap value with € symbol

### PR DESCRIPTION
**Pull request by mskri**
Entering values to input fields overlapped the values with the € symbol. Added some padding to the inputs to fix it.

**Before**
image

**After**
image

### CODE REVIEW

**Comment by rikukissa** [comment]
Interesting 🤔 Is there some specific browser / screen size on which this happens? Just asking as for myself it looks like this even before the change:
image

**Comment by mskri** [comment]
Its looks to be Firefox only issue. Happens on both desktop and mobile versions. Actually, just adding padding is not enough. It shifts the input on non-Firefox browsers too much as the inner `.numeric-input` has padding too.

Desktop
81.0.1 (64-bit)

Mobile
81.1.4 (Build #2015768387)

**Comment by mskri** [comment]
I looked at this with fresh eyes and noticed that on Firefox the `box-sizing` seems to be different from other browsers. Chrome and Safari seems to do `box-sizing: border-box` by default for inputs but Firefox doesn't. That's why on Firefox the added right padding to the `.numeric-input` was overflowing the container it was in.

Removed the padding and added `box-sizing: border-box` to the input keeps the Chrome / Safari looking as before but fixes the overlap on Firefox.

**Comment by rikukissa** [comment]
Brilliant! Seems to be working with all browsers now 👍  Thanks a lot!

**Pull request merged**
