### PR TITLE
English language version

### PR DESCRIPTION
**Pull request by rikukissa**

### CODE REVIEW

**Comment by sam-hosseini** [comment]
```javascript
    en: {
      translation: {
        title: "Dividend or salary?",
        subtitle: "And how much?",
        description: "",
        start: "Start by entering basic information",
        startHelp: "",
        inputsNetFunds: "Company's net assets at the beginning of fiscal year",
        inputsProfitPredition: "",
        inputMinimumIncome: "",
        scenariosTitle: "",
        scenariosDescription: "",
        heatmapGrossLabel: "Gross",
        heatmapTaxLabel: "Tax",
        heatmapDividentLabel: "Dividend",
        heatmapCompanyTaxLabel: "Corporate tax *",
        heatmapSalaryLabel: "Salary",
        heatmapTotalLabel: "Total",
        heatmapNetLabel: "Net amount",
        heatmapCompanyProfit: "Company revenue",
        heatMapCompanyTaxDescription: "",
        calculationsTitle: "Calculations",
        calculationsDescriptionIdealNotCheapest: "",
        calculationsDescriptionIdealCheapest: "",
        cardBestOption: "best option for you",
        cardDivident: "dividend",
        cardSalary: "salary",
        wouldSaveInTaxes: "",
        wouldIncreaseTaxes: "",
        wouldSaveInDividentTax: "",
        wouldIncreaseDividentTax: "",
        and: "and",
        but: "but",
        nextCheapest: "The next cheapest option",
        netIncome: "net income",
        inTotalYouWouldSave: "Approximate total money saved",
        tableNetIncome: "Net income",
        tableSalary: "Salary",
        tableIncomeTax: "Income tax",
        tableDivident: "Dividend",
        tableCapitalGainsTax: "Capital gain tax",
        tableCompanyTax: "Corporate tax",
        tableCompanyTaxOfDivident: "dividend",
        tableTaxesInTotal: "Total taxation",
        informationTitle: "More information?",
        informationDescription: "",
        informationFeedbackButton: "Leave feedback",
        footer: ""
      }
```

**Comment by rikukissa** [comment]
Brilliant! Thank you so much for your help. A testable English language version should be in deploy preview in any minute now 😍 Could you give it a try and see what you think?

**Comment by sam-hosseini** [comment]
> Brilliant! Thank you so much for your help. A testable English language version should be in deploy preview in any minute now 😍 Could you give it a try and see what you think?

My pleasure, thank you as well for putting your time in this weekend on this improvements 🙌🏼

I saw the English version [here](https://deploy-preview-14--tender-roentgen-cd6e75.netlify.app/) and it looks wonderful! There are some tinny issues here and there, but those will be much easier to fix with small PRs once this foundational PR is merged 👍🏼

Great job 🤝

**Comment by rikukissa** [comment]
Thanks a lot for your help! Merged and deployed to live

**Pull request merged**
